language: rust

rust:
  - stable

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo build --release
  - cargo build --release --features=backend-mmap
  - cargo test
  - cargo test --features=backend-mmap
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
